# Generated by Django 4.2.3 on 2023-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_useraccount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user'], name='Account_use_user_id_4631ac_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['account'], name='Account_use_account_a157a7_idx'),
        ),
    ]
