# Generated by Django 4.2.3 on 2023-08-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0004_useraccount_account_use_user_id_4631ac_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
