# Generated by Django 4.2.3 on 2023-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_teaminvitation_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teaminvitation',
            name='Account_tea_role_id_74c378_idx',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='role',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
