# Generated by Django 4.2.3 on 2023-08-07 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_teaminvitation_account_tea_role_id_74c378_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
