# Generated by Django 4.2.3 on 2023-08-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_teaminvitation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='token',
        ),
    ]
