# Generated by Django 4.2.3 on 2023-08-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_rolepermission_userrole_teaminvitation_role_and_more'),
        ('Account', '0008_remove_teaminvitation_token'),
    ]

    operations = [
    ]
