# Generated by Django 4.2.3 on 2023-08-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_merge_20230810_1312'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teaminvitation',
            name='Account_tea_role_id_74c378_idx',
        ),
    ]
