# Generated by Django 4.2.3 on 2023-08-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_merge_20230813_0346'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teaminvitation',
            name='Account_tea_role_id_74c378_idx',
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
    ]
