# Generated by Django 4.2.3 on 2023-08-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_teaminvitation_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.role'),
        ),
    ]
