# Generated by Django 4.2.3 on 2023-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_account_admin',
            field=models.BooleanField(default=True),
        ),
    ]
